apps/crud/urls.py
from django.urls import path

from . import views

app_name = 'crud'

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("create", views.Create.as_view(), name="create"),
    path("edit/<int:pk>", views.Edit.as_view(), name="update"),
    path("delete/<int:pk>", views.Delete.as_view(), name="delete"),
]

apps/ejemplo/urls.py
from django.urls import path

from . import views

app_name = 'ejemplo'

urlpatterns = [
    path("", views.index, name="index"),
    path("indexitem", views.indexitem, name="indexitem"),
    path("create", views.Create.as_view(), name="create"),
    path("create-loading", views.CreateLoading.as_view(), name="create-loading"),
    path("create-sweatalert", views.CreateSweatalert.as_view(), name="create-sweatalert"),
]

plantilladjango/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.ejemplo.urls")),
    path("crud/", include("apps.crud.urls"))    
]

apps/crud/models.py
from django.db import models

# Create your models here.
class CRUDModel(models.Model):
    int = models.IntegerField()
    char = models.CharField(max_length=255)
    text = models.TextField()
    date = models.DateField()

    class Meta:
        verbose_name = 'CRUD_model'
        verbose_name_plural = 'CRUD_models'
        db_table = 'crud_model'
        ordering = ['-id']

apps/ejemplo/models.py
from django.db import models

# Create your models here.

apps/crud/forms.py
from django import forms
import datetime
from .models import CRUDModel

class CRUDForm(forms.ModelForm):
    class Meta:
        model = CRUDModel
        fields = [
            'int',
            'char',
            'text',
            'date',
        ]

        labels = {
            'int': 'Entero',
            'char': 'Alfanumérico',
            'text':'Texto',
            'date':'Fecha',
        }

        widgets = {
            'int': forms.NumberInput(attrs={'placeholder': 'Entero', 'class': 'form-control'}),
            'char': forms.TextInput(attrs={'placeholder': 'Alfanumérico', 'class': 'form-control'}),
            'text': forms.Textarea(attrs={'placeholder': 'Texto'}),
            'date': forms.DateInput(attrs={'type': 'date'}),
        }




   

apps/ejemplo/forms.py
from django import forms

class MiFormulario(forms.Form):
    opciones = [
        ('opcion1', 'Opción 1'),
        ('opcion2', 'Opción 2'),
        ('opcion3', 'Opción 3'),
    ]
    
    clave_pedimento = forms.CharField(
        max_length=100,
        label="Clave de pedimento",
        widget=forms.TextInput(attrs={'placeholder': 'Clave pedimento'})
    )
    tipo_operacion = forms.ChoiceField(
        choices=opciones,
        widget=forms.Select(),
        label="Tipo de operación"
    )
    fecha_inicio = forms.DateField(
        label="Fecha inicio",
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    fecha_fin = forms.DateField(
        label="Fecha fin",
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    descripcion = forms.CharField(
        label="Descripción",
        widget=forms.Textarea(attrs={'placeholder': 'Descripción'})
    )

    # Select 2
    estado = forms.ChoiceField(
        choices=opciones,
        widget=forms.Select(attrs={"data-control": "select2", "data-placeholder": "Elige un estado"}),
        label="Estado"
    )

    checkbox = forms.BooleanField(required=False)

    radio = forms.ChoiceField(
        widget= forms.RadioSelect(),
        choices=opciones, 
    )

class FormularioLoading(forms.Form):
    elemento1 = forms.CharField(max_length=255, label="Elemento 1", widget=forms.TextInput(attrs={'placeholder':'Elemento 1'}))

ejemplo/forms.py
from django import forms

class MiFormulario(forms.Form):
    opciones = [
        ('opcion1', 'Opción 1'),
        ('opcion2', 'Opción 2'),
        ('opcion3', 'Opción 3'),
    ]
     
    clave_pedimento = forms.CharField(
        max_length=100,
        label="Clave de pedimento",
        widget=forms.TextInput(attrs={'placeholder': 'Clave pedimento'})
    )
    tipo_operacion = forms.ChoiceField(
        choices=opciones,
        widget=forms.Select(),
        label="Tipo de operación"
    )
    fecha_inicio = forms.DateField(
        label="Fecha inicio",
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    fecha_fin = forms.DateField(
        label="Fecha fin",
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    descripcion = forms.CharField(
        label="Descripción",
        widget=forms.Textarea(attrs={'placeholder': 'Descripción'})
    )

    # Select 2
    estado = forms.ChoiceField(
        choices=opciones,
        widget=forms.Select(attrs={"data-control": "select2", "data-placeholder": "Elige un estado"}),
        label="Estado"
    )

    checkbox = forms.BooleanField(required=False)

    radio = forms.ChoiceField(
        widget= forms.RadioSelect(),
        choices=opciones, 
    )

class FormularioLoading(forms.Form):
    elemento1 = forms.CharField(max_length=255, label="Elemento 1", widget=forms.TextInput(attrs={'placeholder':'Elemento 1'}))

apps/crud/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import JsonResponse
from .models import CRUDModel
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views.generic import TemplateView, UpdateView, DeleteView, CreateView, FormView
from django_filters.views import FilterView
from .forms import CRUDForm
from .filters import CRUDFilter

class Index(FilterView):
    template_name = 'index.html'
    model = CRUDModel
    context_object_name = 'models'
    filterset_class = CRUDFilter
    paginate_by = 20

class Create(CreateView):
    template_name = 'create.html'
    form_class = CRUDForm
    success_url = reverse_lazy('crud:index')

    def post(self, request):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'sucess': False, 'errors': form.errors})

class Edit(UpdateView):
    model = CRUDModel
    template_name = 'edit.html'
    form_class = CRUDForm
    success_url = reverse_lazy('crud:create')

class Delete(DeleteView):
    model = CRUDModel
    template_name = 'delete.html'
    success_url = reverse_lazy('crud:create')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pk"] = self.kwargs['pk']
        return context

apps/ejemplo/views.py
import time
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.views.generic import FormView

from .forms import MiFormulario, FormularioLoading

def index(request):
    return render(request, "ejemplo/index.html") 

def indexitem(request):
    return render(request, "ejemplo/indexitem.html")

class Create(FormView):
    template_name = 'ejemplo/create.html'
    form_class = MiFormulario

    def post(self, request):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if form.is_valid():
            return JsonResponse({'data': form.data})
        else:
            return JsonResponse({'sucess': False, 'errors': form.errors})

class CreateLoading(FormView):
    template_name = 'ejemplo/create_loading.html'
    form_class = FormularioLoading

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            # Puse un sleep para fines de mostrar el alert con el elemento de loading
            time.sleep(5)
            return redirect(reverse_lazy('ejemplo:index'))
        return render(request, self.template_name, context={'form':form})
    
class CreateSweatalert(FormView):
    template_name = 'ejemplo/create_sweatalert.html'
    form_class = FormularioLoading

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            messages.success(request,'El registro se realizó con éxito.')
            return redirect(reverse_lazy('ejemplo:index'))
        messages.error(request,'No se pudo realizar el registro.')
        return render(request, self.template_name, context={'form':form})

apps/crud/templates/delete.html
{% load static %}

{% block css %}

{% endblock %}

<div class="modal-dialog modal-md" role="document" id="delete-modal">
    <div class="modal-content" >
        <div class="modal-header">
            <h4 class="modal-title">Eliminar modelo</h4>
        </div>
        <form action="{% url 'crud:delete' pk %}" method="POST">

            <div class="modal-body">

                {% csrf_token %}
            
                    <div>
                        <p style="font-size: 18px;color: rgb(58,59,69);">
                            Si eliminas este elemento ya no podrás recuperarlo.
                        </p>
                    </div>

            </div>
        
            <div class="modal-footer">
                <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button>

                <button class="btn btn-danger" type="button" onclick="submit()">Eliminar</button>
            </div>
        </form>
    </div>
</div>

{% block js %}{% endblock %}

apps/crud/templates/index.html
{% load static %}

<div class="container-fluid"> 
    <div class="mainContent container-fluid m-3 ">
        <div class="row container-fluid" style="overflow: hidden;">
            <header class="py-3 mb-4">
                <div class="container-fluid d-flex flex-wrap justify-content-center">
                    <a class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
                        <span class="fw-bold text-anam-secondary" style="font-size:35px">Lista</span>
                    </a>
                    
                </div>
            </header>
        </div>
        <div class="row container-fluid">
            <div class="col-9 d-flex justify-content-between">
                             
            </div>
            
            <div class="col-3 d-flex align-items-center justify-content-end">
                <button  class="btn btn-anam-primary m-1"  data-bs-toggle="collapse" data-bs-target="#filtro" aria-expanded="false"  >Ver Filtros</button> 
            </div>
            
            <div class="collapse"  id="filtro">
                <form id="filter-form" method="GET">
                    <div class="container-fluid d-flex">
                        {% for field in filter.form %}
                            <div class="me-4 ">
                                <label class="form-label" style="font-weight: bold;" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                                <div class="input-group">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="d-flex flex-row-reverse col-12">
                        <button type="submit" class="btn btn-anam-primary m-1">Filtrar</button> 
                        <a href="{% url 'crud:create' %}" class="btn btn-anam-secondary m-1">Limpiar</a>
                    </div>
                </form>
            </div>
            <!-- TABLE -->
            <div class="container-fluid mt-10" style="background: white; border-radius:20px">
                <div class="container-fluid d-flex flex-column p-4 pt-5 mt-3 containerFiltro" style="margin-bottom: 1.6rem;">
                    <div class="container-fluid d-flex justify-content-between">
                        <p class="fs-3 fw-semibold" > Modelos</p>
                        
                    </div>
                    
                    <table class="table table-striped">
                        <thead class="fs-4 fw-bold text-white" style="background: #9f2241;text-transform:uppercase;vertical-align: middle">
                            <tr>
                                <th class="ps-3" style="border-radius: 20px 0px 0px 0px;">Entero</th>
                                <th>Alfanumérico</th>
                                <th>Texto</th>
                                <th>Fecha</th>
                                <th class="pe-3" style="border-radius: 0px 20px 0px 0px;">Acciones</th>
                            </tr>
                        </thead>
                        
                        
                        <tbody class="text-center" style="vertical-align: middle">
                            {% for model in models %}
                                <tr>
                                    <td>
                                        {{model.int}}
                                    </td>

                                    <td>
                                        {{model.char}}
                                    </td>
                                    <td>
                                        {{model.text}}
                                    </td>

                                    <td>
                                        {{model.date}}
                                    </td>
                                    <td >
                                        <a href="{% url 'crud:update' model.id %}" class="btn btn-outline btn-outline-secondary btn-active-light-secondary" style="border-radius: 100px; border-width: 2px;" href="#">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <button type="button" class="btn btn-outline btn-outline-danger btn-active-danger" data-bs-target="#delete-modal" onclick="openDeleteModal('{% url 'crud:delete' model.id %}')" style="border-radius: 100px; border-width: 2px;">
                                            <i class="fas fa-trash"></i>
                                            
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <br/><br/>
                    <div style="text-align: center;">
                        <span style="color: rgba(91, 114, 130, 0.5) !important; cursor: pointer;">
                            {% if page_obj.has_previous %}
                                <a 
                                hx-get="{{request.path}}" 
                                hx-target="#htmx-table"
                                hx-vals='{"page": "1"}'
                                hx-swap="innerHTML"
                                >
                                    <img src="{% static 'src/prev_pg.svg'%}" style=" display: inline-block;vertical-align: middle;">
                                    Primera
                                </a>

                                <a 
                                hx-get="{{request.path}}" 
                                hx-target="#htmx-table"
                                hx-vals='{"page": "{{page_obj.previous_page_number}}"}'
                                >
                                    <img src="{% static 'src/prevMini_pg.svg'%}" style=" display: inline-block;vertical-align: middle; padding-left: 10px">
                                    <span style="padding-right: 10px;">Anterior</span>  
                                </a>
                            {% endif %}

                            <span class="active-page text-white px-3 py-2" style="background-color: #bc955c;border-radius:8px">{{page_obj.number}}</span>

                            {% if page_obj.has_next %}
                                <a
                                hx-get="{{request.path}}" 
                                hx-target="#htmx-table"
                                hx-vals='{"page": "{{page_obj.next_page_number}}"}'
                                >
                                    <span style="padding-left: 10px;">Siguiente</span> 
                                    <img src="{% static 'src/nextMini_pg.svg'%}" style=" display: inline-block;vertical-align: middle; padding-right: 10px">
                                </a>

                                <a 
                                hx-get="{{request.path}}"
                                hx-target="#htmx-table"
                                hx-vals='{"page": "{{page_obj.paginator.num_pages}}"}'
                                >
                                    Última 
                                    <img src="{% static 'src/next_pg.svg'%}" style=" display: inline-block;vertical-align: middle;"></span>
                                </a>
                            {% endif %}

                        </div>
                        <div class="text-end">
                            <a>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                        </div>

                        <br/><br/>                        
                    </div>
                </div>
            </div>
            
        </div>

        <!-- MODAL ERROR -->
        <div id="myModal" class="modal  fade modal-error pr-5" style="z-index: 9999;  " role="dialog">
            <div class="modal-dialog modal-dialog-top-right">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="d-inline-flex align-middle">
                        <div class="error-svg-container">
                            <img src="static\assets\src\cross-circle-svgrepo-com.svg" class="error-svg pe-2" style="color: red" alt="cross circle">
                        </div>
                        <h4 class="modal-title pt-2">¡Error!</h4>
                    </div>
                    <div class="modal-body">
                        <p id="searchResult"></p>
                    </div>
                    <div class="d-flex flex-row-reverse btn-cerrar btn-sm">
                        <button type="button" style="background-color: #9f2241; color:white;" class="btn btn-default" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div> 
        
        
    </div>
    
    <!-- MODAL EXITO DESCARGA -->
    <div class="toast-container top-0 end-0 p-3" data-bs-config='{"delay":5000}'>
        <div id="liveToast" class="toast  successNotifJustificar" role="alert" aria-live="assertive" aria-atomic="true">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                </svg>
                <strong class="me-auto" style="margin-left: 3px;">Success</strong>
            </div>
            <div class="toast-body">
                El pedimento con folio <a class="folioSuccess"> FOLIO </a> fue justificado correctamente.
            </div>
        </div>
    </div>   
</div> 

apps/ejemplo/templates/ejemplo/create.html
{% extends 'layout.html' %} 
{% block title %}
    Create
{% endblock %}

{% block css %} {% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container-fluid" > 
    <div class="container-fluid m-3">
        <a href="{% url 'ejemplo:indexitem' %}" type="button" class="btn btn-sm btn-secondary mb-3" style="border-radius: 20px;"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                </svg>&nbsp; &nbsp; Volver &nbsp;&nbsp;
        </a>
        <div class="d-flex justify-content-between align-items-center">
            <div class="py-3 mb-4">
                <div class="container-fluid d-flex flex-wrap justify-content-center mt-4">
                    <a class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
                        <span class="fs-1 fw-bold">Añadir</span>
                    </a> 
                </div>
                <div class="container-fluid d-flex flex-wrap">
                    <h4> Los campos que tengan el <span style="color: red;">*</span> tendrán que ser llenados obligatoriamente. </h4>
                </div>
            </div>

            <div class="d-inline-flex align-items-end justify-content-end col-4">
                <a href="{% url 'ejemplo:indexitem' %}"  class="btn btn-anam-secondary m-1" > Cancelar </a>
                <button type="submit" form="create-form" class="btn btn-anam-primary m-1">Guardar</button>
            </div>
        </div>
    
        <div  class="container-fluid px-10 py-5" >
            <div class="p-4 pt-5" style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.1)">
                <form id="create-form" role="form" method="post">
                    {% csrf_token %}
                    
                    <div class="row">
                        <div class="form-group mb-3 col-6">
                            <strong>{{ form.clave_pedimento | as_crispy_field }}</strong>
                        </div>
                        <div class="form-group mb-3 col-6">
                            <strong>{{ form.tipo_operacion | as_crispy_field }}</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group mb-3 col-6">
                            <strong>{{ form.fecha_inicio | as_crispy_field }}</strong>
                        </div>
                        <div class="form-group mb-3 col-6">
                            <strong>{{ form.fecha_fin | as_crispy_field }}</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group mb-3 ">
                            <strong>{{ form.descripcion | as_crispy_field }}</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group mb-3 ">
                            <strong>{{ form.estado | as_crispy_field }}</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group mb-3 ">
                            <strong>{{ form.checkbox | as_crispy_field }}</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group mb-3 radio-group">
                            <strong>{{ form.radio | as_crispy_field }}</strong>
                        </div>
                    </div>
                </form>
            </div>
        </div> 
    </div>    
</div>
{% endblock %}

{% block js %}

{% endblock  %}

apps/ejemplo/templates/ejemplo/create_sweatalert.html
{% extends 'layout.html' %} 
{% block title %}
    Create
{% endblock %}

{% block css %} {% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container-fluid" > 
    <div class="container-fluid m-3">
        <a href="{% url 'ejemplo:indexitem' %}" type="button" class="btn btn-sm btn-secondary mb-3" style="border-radius: 20px;"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                </svg>&nbsp; &nbsp; Volver &nbsp;&nbsp;
        </a>
        <div class="d-flex justify-content-between align-items-center">
            <div class="py-3 mb-4">
                <div class="container-fluid d-flex flex-wrap justify-content-center mt-4">
                    <a class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
                        <span class="fs-1 fw-bold">Añadir</span>
                    </a> 
                </div>
                <div class="container-fluid d-flex flex-wrap">
                    <h4> Los campos que tengan el <span style="color: red;">*</span> tendrán que ser llenados obligatoriamente. </h4>
                </div>
            </div>

            <div class="d-inline-flex align-items-end justify-content-end col-4">
                <a href="{% url 'ejemplo:indexitem' %}"  class="btn btn-anam-secondary m-1" > Cancelar </a>
                <button type="submit" form="create-form" class="btn btn-anam-primary m-1">Guardar</button>
            </div>
        </div>
    
        <div  class="container-fluid px-10 py-5" >
            <div class="p-4 pt-5" style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.1)">
                <form id="create-form" role="form" method="post">
                    {% csrf_token %}
                    
                    <div class="row">
                        <div class="form-group mb-3 col-6">
                            <strong>{{ form.elemento1 | as_crispy_field }}</strong>
                        </div>
                    </div>
                </form>
            </div>
        </div> 
    </div>    
</div>
{% endblock %}

{% block js %}


{% endblock  %}

templates/sidebar.html
{% load static %}

<!--begin::sidebar-->
<div id="kt_app_sidebar" class="app-sidebar flex-column" data-kt-drawer="true" data-kt-drawer-name="app-sidebar"
data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="225px"
data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_app_sidebar_mobile_toggle">

    <!--begin::Logo-->
    <div class="app-sidebar-logo px-6" id="kt_app_sidebar_logo">
        <!--begin::Logo image-->
        <a href="/">
            <img alt="Logo" src="{% static 'src/logoh.png'%}" class="h-45px app-sidebar-logo-default" />
            <img alt="Logo" src="{% static 'src/logo.png'%}" class="h-30px app-sidebar-logo-minimize" />
        </a>
        <!--end::Logo image-->
        <!--begin::Sidebar toggle-->
        <!--begin::Minimized sidebar setup:
            if (isset($_COOKIE["sidebar_minimize_state"]) && $_COOKIE["sidebar_minimize_state"] === "on") {
                1. "src/js/layout/sidebar.js" adds "sidebar_minimize_state" cookie value to save the sidebar minimize state.
                2. Set data-kt-app-sidebar-minimize="on" attribute for body tag.
                3. Set data-kt-toggle-state="active" attribute to the toggle element with "kt_app_sidebar_toggle" id.
                4. Add "active" class to to sidebar toggle element with "kt_app_sidebar_toggle" id.
            }
        -->
        <div id="kt_app_sidebar_toggle" class="app-sidebar-toggle btn btn-icon btn-shadow btn-sm btn-color-muted btn-active-color-primary body-bg h-30px w-30px position-absolute top-50 start-100 translate-middle rotate" data-kt-toggle="true" data-kt-toggle-target="body" data-kt-toggle-name="app-sidebar-minimize">
            <span class="ki-duotone ki-double-left fs-2 rotate-180"><span class="path1"></span><span class="path2"></span></span>
        </div>
        <script type="text/javascript">
            var sidebar_toggle = document.getElementById("kt_app_sidebar_toggle");  // Get the sidebar toggle button element
            if ("{{ request.COOKIES.sidebar_minimize_state }}" === "on" || "{{ request.COOKIES.sidebar_minimize_state }}" == "")	{
                document.body.setAttribute("data-kt-app-sidebar-minimize", "on");  // Set the 'data-kt-app-sidebar-minimize' attribute for the body tag
                sidebar_toggle.setAttribute("data-kt-toggle-state", "active");  // Set the 'data-kt-toggle-state' attribute for the sidebar toggle button
                sidebar_toggle.classList.add("active");  // Add the 'active' class to the sidebar toggle button
            }
        </script>
        <!--end::Sidebar toggle-->
    </div>
    <!--end::Logo-->

    <!--begin::sidebar menu-->
    <div class="app-sidebar-menu overflow-hidden flex-column-fluid">
        <!--begin::Menu wrapper-->
        <div id="kt_app_sidebar_menu_wrapper" class="app-sidebar-wrapper hover-scroll-overlay-y my-5" data-kt-scroll="true" data-kt-scroll-activate="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer" data-kt-scroll-wrappers="#kt_app_sidebar_menu" data-kt-scroll-offset="5px" data-kt-scroll-save-state="true">
            <!--begin::Menu-->
            <div class="menu menu-column menu-rounded menu-sub-indention px-3" id="#kt_app_sidebar_menu" data-kt-menu="true" data-kt-menu-expand="false">
                <!--begin:Menu item-->
                <div class="menu-item">
                    <!--begin:Menu link-->
                    <a class="menu-link" href="{% url 'ejemplo:index' %}">
                        <span class="menu-icon"><span class="ki-duotone ki-book fs-2"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></span></span>
                        <span class="menu-title">Consultar pedimentos</span>
                    </a>
                    <!--end:Menu link-->
                    <a class="menu-link" href="{% url 'ejemplo:indexitem' %}">
                        <span class="menu-icon"><span class="ki-duotone ki-book fs-2"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></span></span>
                        <span class="menu-title">Ejemplo vista</span>
                    </a>

                    <a class="menu-link" href="{% url 'crud:create' %}">
                        <span class="menu-icon"><span class="ki-duotone ki-book fs-2"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></span></span>
                        <span class="menu-title">Ejemplo CRUD</span>
                    </a>

                    <a class="menu-link" href="{% url 'ejemplo:create-loading' %}">
                        <span class="menu-icon"><span class="ki-duotone ki-book fs-2"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></span></span>
                        <span class="menu-title">Ejemplo CRUD con loading</span>
                    </a>
                    <a class="menu-link" href="{% url 'ejemplo:create-sweatalert' %}">
                        <span class="menu-icon"><span class="ki-duotone ki-book fs-2"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></span></span>
                        <span class="menu-title">Ejemplo CRUD con sweatalert</span>
                    </a>
                </div>
                <!--end:Menu item-->
            </div>
            <!--end::Menu-->
        </div>
        <!--end::Menu wrapper-->
    </div>
    <!--end::sidebar menu-->
    <!--begin::Footer-->
    <div class="app-sidebar-footer flex-column-auto pt-2 pb-6 px-6" id="kt_app_sidebar_footer">
    </div>
    <!--end::Footer-->
</div>
<!--end::sidebar-->